apiVersion: v1
kind: Namespace
metadata:
  name: openshift-cluster-group-upgrades
  annotations:
    workload.openshift.io/allowed: management
  labels:
    app.kubernetes.io/name: talm-operator
    app.kubernetes.io/component: talm
    openshift.io/cluster-monitoring: "true"
